# fly.toml app configuration file generated for server-falling-water-119 on 2024-08-05T19:49:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-falling-water-119'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 8765
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
